name: real_test
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  lottie: ^3.1.2
  camera: ^0.11.0+1
  path_provider: ^2.1.3
  video_player: ^2.9.1
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  awesome_snackbar_content: ^0.1.3
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  image_picker: ^1.1.2
  get: ^4.6.6
  http: ^1.2.2
  json_annotation: ^4.9.0
  flutter_dotenv: ^5.1.0
  dio: ^5.5.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # To add fonts to your application, add a fonts section, like this:
  fonts:
    - family: Maple
      fonts:
        - asset: assets/fonts/MapleStory.ttf

